#!/bin/sh
case "$1" in
  start)
    /bin/screen -d -m /opt/app/run.sh
    ;;
  stop)
    /bin/screen -X -S 0 quit
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0